name: Android CI

on:
  push:
    branches: [ "add-action" ]
    tags:
      - '*'
    
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew build assembleDebug --stacktrace
        mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/gads-stream.apk
        zip -j gads-stream.zip app/build/outputs/apk/debug/gads-stream.apk
    - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: gads-stream.zip
          asset_name: gads-stream.zip
          tag: ${{ github.ref }}
          overwrite: true
#    - name: Upload APK Debug
#      uses: actions/upload-artifact@v3
#      with:
#        name: gads-stream
#        path: app/build/outputs/apk/debug/app-debug.apk
#    - name: Download APK from build
#      uses: actions/download-artifact@v3
#      with:
#        name: gads-stream
#    - name: Create Release
#      id: create_release
#      uses: actions/create-release@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        tag_name: latest
#        release_name: latest
#    - name: Upload Release APK
#      id: upload_release_asset
#      uses: actions/upload-release-asset@v1.0.1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        upload_url: ${{ steps.create_release.outputs.upload_url }}
#        asset_path: apk/app-debug.apk
#        asset_name: gads-stream.apk
#        asset_content_type: application/zip
