name: Android CI

on:
  push:
    tags:
      - '*'
    
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew build assembleDebug --stacktrace
        mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/gads-stream.apk
        zip -j gads-stream.zip app/build/outputs/apk/debug/gads-stream.apk
    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: gads-stream.zip
        asset_name: gads-stream.zip
        tag: ${{ github.ref_name }}
        overwrite: true
